### ISSUE TITLE
 Execute R script not working in PDI 5.1 CE 

### ISSUE THREAD

**Issue by sumit140** [dekarlab/pentahor#10]
Hi 
I am using PDI 5.1.0 CE and installed the Execute R script plugin from market place .it was successfully installed and i can see execute R Script step under scripting folder.when i am drawing the step then i m getting this error:

org.pentaho.di.core.exception.KettlePluginException:
Unexpected error loading class:
de/dekarlab/pentahor/plugin/PRCalcMeta : Unsupported major.minor version 51.0

at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:484)
at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:336)
at org.pentaho.di.ui.spoon.Spoon.newStep(Spoon.java:6470)
at org.pentaho.di.ui.spoon.trans.TransGraph$5.drop(TransGraph.java:612)
at org.eclipse.swt.dnd.DNDListener.handleEvent(Unknown Source)
at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
at org.eclipse.swt.dnd.DropTarget.Drop(Unknown Source)
at org.eclipse.swt.dnd.DropTarget$3.method6(Unknown Source)
at org.eclipse.swt.internal.ole.win32.COMObject.callback6(Unknown Source)
at org.eclipse.swt.internal.ole.win32.COM.DoDragDrop(Native Method)
at org.eclipse.swt.dnd.DragSource.drag(Unknown Source)
at org.eclipse.swt.dnd.DragSource.access$000(Unknown Source)
at org.eclipse.swt.dnd.DragSource$1.handleEvent(Unknown Source)
at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1297)
at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7801)
at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9130)
at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:638)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.pentaho.commons.launcher.Launcher.main(Launcher.java:151)
Caused by: java.lang.UnsupportedClassVersionError: de/dekarlab/pentahor/plugin/PRCalcMeta : Unsupported major.minor version 51.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromThisLoader(KettleURLClassLoader.java:76)
at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:99)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
at org.pentaho.di.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:466)
... 29 more

Also i have added the following variable:

R_HOME:C:\Program Files\R\R-3.1.3
R_LIBS_USER :C:\Program Files\R\R-3.1.3\library
Path :C:\Program Files\R\R-3.1.3\bin\i386

Can any one tell me how i can use Execute R script with PDI 5.1.0.

Regards
Sumit

**Comment by sumit140** [comment]
is there any way to resolve that issue?

**Comment by dekarlab** [comment]
Hi, the plugin code is compiled with java 7. you should install java7.
