### ISSUE TITLE
Table input and vector output fails

### ISSUE THREAD

**Issue by pcserna** [dekarlab/pentahor#14]
Hello,

I would like to process and forecast weekly data. The weekly data processed as a table.
The forecast has 8 records ahead. 
If I choose list as the OUTPUT then only the first row of the result is returned. 
If I set OUTPUT as vector, then I get the following error lines:
ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Unexpected error
ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : org.pentaho.di.core.exception.KettleException: 
Error by executing R script: null
 at java.lang.Thread.run (null:-1)
 at org.pentaho.di.trans.step.RunThread.run (RunThread.java:62)
 at de.dekarlab.pentahor.plugin.PRCalc.processRow (PRCalc.java:214)
 at de.dekarlab.pentahor.plugin.PRCalc.runR (PRCalc.java:84)
 at de.dekarlab.pentahor.RRunner.run (RRunner.java:139)
 at de.dekarlab.pentahor.RRunner.getVariables (RRunner.java:246)
	at de.dekarlab.pentahor.plugin.PRCalc.processRow(PRCalc.java:251)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at de.dekarlab.pentahor.RRunner.getVariables(RRunner.java:246)
	at de.dekarlab.pentahor.RRunner.run(RRunner.java:139)
	at de.dekarlab.pentahor.plugin.PRCalc.runR(PRCalc.java:84)
	at de.dekarlab.pentahor.plugin.PRCalc.processRow(PRCalc.java:214)
	... 2 more
child index = 0, logging object : org.pentaho.di.core.logging.LoggingObject@45f47597 parent=c49356bf-4b18-4d7e-be32-04ca11813394

Running 7.1 Spoon, jdk1.8.0_121 (64 bit), R-3.4.0.
The test files run fine.
Hereby I enclose my test files.
Thank you for your help.
Best regards,
Peter

[FC.zip](https://github.com/dekarlab/pentahor/files/1149006/FC.zip)

**Comment by bessae2** [comment]
Hi @pcserna, same problem here, did you find a solution?

Thanks

**Comment by pcserna** [comment]
Hello @evanbessa,
I did it in an ugly way:

OUTPUT<-list("mean1"=m[1], "mean2"=m[2], "mean3"=m[3], "mean4"=m[4], "mean5"=m[5], "mean6"=m[6], "mean7"=m[7],"mean8"=m[8], "low1"=l[1], "low2"=l[2], "low3"=l[3], "low4"=l[4], "low5"=l[5], "low6"=l[6], "low7"=l[7],"low8"=l[8], "high1"=h[1], "high2"=h[2], "high3"=h[3], "high4"=h[4], "high5"=h[5], "high6"=h[6], "high7"=h[7], "high8"=h[8])

These are the output variable columns in the R step.
Hope, this helps!
Br,
Peter

**Comment by bessae2** [comment]
Hello @pcserna 

It's not ugly if it's works haha 
I change my approach, i executing using shell script option.

Thank you very much for your help.

Br,

Evan
